model = "gpt-5.4"
model_reasoning_effort = "low"
[features]
collaboration_modes = true

[projects."/Users/dts-da002n/00_project/dotfiles"]
trust_level = "trusted"

[projects."/Users/dts-da002n/00_project/escon"]
trust_level = "trusted"

[projects."/Users/dts-da002n/00_project/sumire"]
trust_level = "trusted"

[projects."/Users/dts-da002n/00_project/poc"]
trust_level = "trusted"

[projects."/Users/dts-da002n/Documents"]
trust_level = "trusted"

[projects."/Users/dts-da002n/00_project/da-intra-apps-hub"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"
