onboarding = false
[keys]
prefix = "ctrl+a"
next_tab = ["prefix+n", "cmd+alt+right"]
previous_tab = ["prefix+p", "cmd+alt+left"]
split_horizontal = ["prefix+minus", "prefix+s"]

[theme]
name = "rose-pine"
auto_switch = false
